version: "3"
services:
    postgre_IO:
        container_name: postgre_IO
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: zaq1@WSX
            POSTGRES_DB: io2024
        ports:
            - "5432:5432"
        networks:
            - io2024-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
networks:
    io2024-network:
        driver: bridge
        external: true
